export const SkillList = {
  acumen: [
    'devicon-react-original',
    'devicon-javascript-plain',
    'devicon-nodejs-plain',
    'devicon-express-original',
    'devicon-mongodb-plain',
    'devicon-firebase-plain',
    'devicon-html5-plain',
    'devicon-css3-plain',
    'devicon-sass-original',
    'devicon-jquery-plain',
    'devicon-bootstrap-plain',
    'devicon-wordpress-plain',
    'devicon-git-plain',
    'devicon-heroku-original',
    'devicon-npm-original-wordmark',
  ],
  competencies: [
    'Mobile-first responsive design',
    'Cross-browser compatibility',
    'Testing and debugging',
    'UI / UX design',
  ],
  values: [
    'Creative and critical thinking',
    'Emotional intelligence',
    'Growth mindset',
    'Effective communication',
    'Open-mindedness and adaptability',
    'Cross-functional collaboration',
    'Time management and organization',
    'Servant leadership',
  ],
};
